CC = gcc
FLAGS = -Wall -g

default: test

span.o: span.c span.h
	$(CC) $(FLAGS) span.c -c -o $@

# Write the remaining rules below!
# 1. queries.c should be built into queries.o
# 2. span.o, queries.o, and test.c should be linked for the "test" target
# 3. There should be a "clean" PHONY target that removes all .o files and "test" itself



